# Welcome to Jekyll!
# https://jekyllrb.com/docs/configuration/
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Some are specific to the jekyll-seo plugin
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: Patrick Carlson
description: Personal site for Patrick Carlson.  Resume, contact information, projects, and more.
author: Patrick Carlson
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://carlsonp.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
#theme: minima #<- replaced with a customized version of minima
plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.  These files will not be copied into the '_site' directory
# for deployment.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - create-pdfs.ps1
  - create-pdfs.sh
